### ISSUE TITLE
Migrating from 4.4 to 5.4.0

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [devnull-tools/trugger#1]
How can we migrate the following code written on the version 4.4 to the version 5.4.0? (This examples uses Kotlin, but a Java solution will be OK)

`element().that(isAnnotatedWith<AnnotatedElement>(Id::class.java).or(isAnnotatedWith<AnnotatedElement>(EmbeddedId::class.java))).`in`(this).value<Any>();`

**Comment by ataxexe** [comment]
Just replace `that` with `filter` and `isAnnotatedWith` with `annotatedWith`.

I need to apologize, I'm constantly changing the API without providing migration guides. Right now I'm planning the v6 release with a lot of changes (the `value()` will be `getValue()`, for example).

It may sound like the API isn't mature, but since this project started in 2009, I'm constantly improving my skills and trying to reflect it on the framework. But I really need to apologize.

Oh! And thank you for using it. I didn't know people use it (apart from me and a couple of friends).

;)

**Comment by Danilo-Araujo-Silva** [comment]
Hi, thank you about your answer.

The truth is I think your library is a very useful one, it is very handy to work with annotations and find an arbitrary entity primary key, for example. We can create a structure really powerful with this.

To set a value, instead of value `.value(myValue)`, should we use `.set(myValue)`?

Thanks a lot ;)

**Comment by ataxexe** [comment]
Exactly! I think is not a good name, so that's why I renamed both to `getValue` and `setValue` in version 6. If you wan't to give v6 a try just clone the [branch](https://github.com/devnull-tools/trugger/tree/release/6.0) and do a `mvn install`. It should be released this week.

I'm planning something more functional in this version. You can, for example, do something like this:
```
String value = reflect()
  .field("aStringField")
  .from(myInstance)
  .and(getValue());
```
[ ]'s
